Repository petezhuang/builder, pull requests merged in 2025-08, with the labels that each got.

#29 refactor(spx-gui):move importSvgToCanvas method out of painter component
  spx-gui/src/components/editor/common/painter/painter.vue
  spx-gui/src/components/editor/common/painter/utils/loader.vue
  spx-gui/src/components/editor/common/painter/utils/svg-importer.vue
Labels: enhancement

#46 refactor(spx-gui):event delegator
  spx-gui/src/components/editor/common/painter/painter.vue
  spx-gui/src/components/editor/common/painter/utils/delegator.ts
Labels: refactor

#69 doc: add document of clip
  spx-algorithm/docs/v1.md
Labels: documentation

#70 doc: add document of test theme classifiation
  spx-algorithm/docs/v2.md
Labels: documentation, algorithm

#73 feature: add svg database to current project
  spx-algorithm/resource/vector_db/README_vector_db.md
  spx-algorithm/resource/vector_db/__pycache__/vector_database.cpython-312.pyc
  spx-algorithm/resource/vector_db/__pycache__/vector_db_utils.cpython-312.pyc
  spx-algorithm/resource/vector_db/batch_example_db/index.faiss
  spx-algorithm/resource/vector_db/batch_example_db/metadata.pkl
  spx-algorithm/resource/vector_db/cute.svg
  spx-algorithm/resource/vector_db/cute2.svg
  spx-algorithm/resource/vector_db/database_metadata.json
  spx-algorithm/resource/vector_db/demo_vector_db.py
  spx-algorithm/resource/vector_db/demo_vector_db/index.faiss
  spx-algorithm/resource/vector_db/demo_vector_db/metadata.pkl
  spx-algorithm/resource/vector_db/dog.svg
  spx-algorithm/resource/vector_db/example_db/index.faiss
  spx-algorithm/resource/vector_db/example_db/metadata.pkl
  spx-algorithm/resource/vector_db/requirements_vector_db.txt
  spx-algorithm/resource/vector_db/simple_usage_example.py
  spx-algorithm/resource/vector_db/vector_database.py
  spx-algorithm/resource/vector_db/vector_db_utils.py
Labels: algorithm, feature

#79 feat(spx-backend):add img-recommend interface and sql file
  .gitignore
  spx-backend/AI_RESOURCE_MODELS_INTEGRATION.md
  spx-backend/cmd/spx-backend/get_health.yap
  spx-backend/cmd/spx-backend/post_images_recommend.yap
  spx-backend/cmd/spx-backend/xgo_autogen.go
  spx-backend/docs/IMAGE_RECOMMENDATION_API.md
  spx-backend/internal/config/config.go
  spx-backend/internal/controller/image_recommend.go
  spx-backend/internal/model/ai_resource.go
  spx-backend/internal/model/ai_resource_test.go
  spx-backend/sql/create_tables.sql
Labels: feature

#80 feat(spx-backend):add provider to themeType
  spx-backend/cmd/spx-backend/xgo_autogen.go
  spx-backend/internal/controller/svg.go
  spx-backend/internal/controller/theme.go
  spx-backend/internal/controller/theme_test.go
Labels: feature

#85 fix: fix svg interface and add kodo url to sql
  spx-backend/cmd/spx-backend/xgo_autogen.go
  spx-backend/internal/controller/image_recommend.go
  spx-backend/internal/controller/svg.go
Labels: bug

#89 feat(spx-gui): add draw circle tool
  spx-gui/src/components/editor/common/painter/components/circle_tool.vue
  spx-gui/src/components/editor/common/painter/painter.vue
  spx-gui/src/components/editor/common/painter/utils/delegator.ts
Labels: feature

#94 fix(spx-gui): fix wrong svg import logic
  spx-gui/src/components/editor/common/painter/painter.vue
  spx-gui/src/components/editor/common/painter/utils/import-export-manager.ts
Labels: bug

#96 fix(spx-gui): fix change spirte change logic
  spx-gui/src/components/editor/common/painter/painter.vue
Labels: bug

#98 fix(spx-gui): fix draw sprite the preview flash
  spx-gui/src/components/editor/preview/stage-viewer/SpriteNode.vue
  spx-gui/src/utils/file.ts
Labels: bug

#101 feat(spx-gui): New aigc logic
  spx-gui/src/apis/picgc.ts
  spx-gui/src/components/editor/common/painter/components/aigc/generator.vue
  spx-gui/src/components/editor/common/painter/painter.vue
  spx-gui/src/components/editor/common/painter/utils/import-export-manager.ts
Labels: feature

#104 fix(spx-gui): fix type error of promptInput
  spx-gui/src/components/editor/common/painter/components/aigc/promptInput.vue
Labels: bug

#106 fix(spx-backend):add provider param to img-recommend interface
  spx-backend/internal/controller/image_recommend.go
Labels: bug
